"""Final schema alignment

Revision ID: 2127cec5aaab
Revises: 97c019b435ee
Create Date: 2025-01-23 14:09:45.786056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2127cec5aaab'
down_revision = '97c019b435ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        # Removed drop constraint for unnamed foreign key
        batch_op.create_foreign_key('fk_quote_user', 'user', ['user_id'], ['id'])
        batch_op.drop_column('rep_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rep_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_quote_user', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['rep_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
