"""Convert dimensions to separate columns

Revision ID: 26e7c9f5a512
Revises: a56da157fd36
Create Date: 2025-01-23 18:47:07.734344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26e7c9f5a512'
down_revision = 'a56da157fd36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('length', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('width', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('quantity_per_ctn', sa.Integer(), nullable=False))
        batch_op.drop_column('quantity_per_carton')
        batch_op.drop_column('weight_kg')
        batch_op.drop_column('width_cm')
        batch_op.drop_column('height_cm')
        batch_op.drop_column('length_cm')

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('length', sa.Numeric(precision=6, scale=1), nullable=False, comment='Length in centimeters'))
        batch_op.add_column(sa.Column('width', sa.Numeric(precision=6, scale=1), nullable=False, comment='Width in centimeters'))
        batch_op.add_column(sa.Column('height', sa.Numeric(precision=6, scale=1), nullable=False, comment='Height in centimeters'))
        batch_op.add_column(sa.Column('weight', sa.Numeric(precision=8, scale=2), nullable=False, comment='Weight in kilograms'))
        batch_op.add_column(sa.Column('quantity_per_ctn', sa.Integer(), nullable=False, comment='Units per carton'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_column('quantity_per_ctn')
        batch_op.drop_column('weight')
        batch_op.drop_column('height')
        batch_op.drop_column('width')
        batch_op.drop_column('length')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('length_cm', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('height_cm', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('width_cm', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('weight_kg', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('quantity_per_carton', sa.INTEGER(), nullable=False))
        batch_op.drop_column('quantity_per_ctn')
        batch_op.drop_column('weight')
        batch_op.drop_column('height')
        batch_op.drop_column('width')
        batch_op.drop_column('length')

    # ### end Alembic commands ###
