"""Add created_by relationship to Product

Revision ID: 519cef9362b3
Revises: 98aee2c6aa04
Create Date: 2025-01-24 08:27:05.118129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '519cef9362b3'
down_revision = '98aee2c6aa04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_products_created_by_id', 'user', ['created_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by_id')

    # ### end Alembic commands ###
