"""Add name column to Product model

Revision ID: 98aee2c6aa04
Revises: edd2b27fc7ae
Create Date: 2025-01-24 08:08:28.421900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98aee2c6aa04'
down_revision = 'edd2b27fc7ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.alter_column('production_time',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('production_time',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('name')

    # ### end Alembic commands ###
