"""Update product_sku foreign key length

Revision ID: b87312672c08
Revises: 92aef36e62c0
Create Date: 2025-01-24 09:49:12.351346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b87312672c08'
down_revision = '92aef36e62c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_tiers', schema=None) as batch_op:
        batch_op.alter_column('product_sku',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_tiers', schema=None) as batch_op:
        batch_op.alter_column('product_sku',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
