"""Initial migration

Revision ID: v1
Revises: 
Create Date: 2025-01-23 09:28:25.279003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'v1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dimensional_weight_divisor', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MARKETING', 'USER', name='role'), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('remember_token', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'LOCKOUT', name='actiontype'), nullable=False),
    sa.Column('entity_type', sa.Enum('QUOTE', 'PRODUCT', 'USER', 'CONFIG', name='entitytype'), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('vendor_name', sa.String(length=100), nullable=False),
    sa.Column('vendor_part_number', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('width_cm', sa.Float(), nullable=False),
    sa.Column('length_cm', sa.Float(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('quantity_per_carton', sa.Integer(), nullable=False),
    sa.Column('moq', sa.Integer(), nullable=False),
    sa.Column('package_type', sa.String(length=100), nullable=True),
    sa.Column('imprint_location', sa.String(length=100), nullable=True),
    sa.Column('imprint_dimensions', sa.String(length=50), nullable=True),
    sa.Column('imprint_types', sa.String(length=200), nullable=True),
    sa.Column('production_time', sa.String(length=50), nullable=True),
    sa.Column('stock_date', sa.Date(), nullable=True),
    sa.Column('in_spreadsheet', sa.Boolean(), nullable=True),
    sa.Column('price_list_created', sa.Boolean(), nullable=True),
    sa.Column('new_products_sheet_created', sa.Boolean(), nullable=True),
    sa.Column('in_qb', sa.Boolean(), nullable=True),
    sa.Column('in_web', sa.Boolean(), nullable=True),
    sa.Column('config_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['configurations.id'], ),
    sa.PrimaryKeyConstraint('sku')
    )
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('rep_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('product_sku', sa.String(length=50), nullable=False),
    sa.Column('quantity1', sa.Integer(), nullable=False),
    sa.Column('quantity2', sa.Integer(), nullable=True),
    sa.Column('quantity3', sa.Integer(), nullable=True),
    sa.Column('air_freight1', sa.Float(), nullable=True),
    sa.Column('ocean_freight1', sa.Float(), nullable=True),
    sa.Column('markup1', sa.Float(), nullable=True),
    sa.Column('quote_price1', sa.Float(), nullable=False),
    sa.Column('air_freight2', sa.Float(), nullable=True),
    sa.Column('ocean_freight2', sa.Float(), nullable=True),
    sa.Column('markup2', sa.Float(), nullable=True),
    sa.Column('quote_price2', sa.Float(), nullable=True),
    sa.Column('air_freight3', sa.Float(), nullable=True),
    sa.Column('ocean_freight3', sa.Float(), nullable=True),
    sa.Column('markup3', sa.Float(), nullable=True),
    sa.Column('quote_price3', sa.Float(), nullable=True),
    sa.Column('pdf_data', sa.LargeBinary(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('last_printed', sa.DateTime(), nullable=True),
    sa.CheckConstraint('quantity2 > quantity1 OR quantity2 IS NULL', name='check_quantity_order_1_2'),
    sa.CheckConstraint('quantity3 > quantity2 OR quantity3 IS NULL', name='check_quantity_order_2_3'),
    sa.ForeignKeyConstraint(['product_sku'], ['products.sku'], ),
    sa.ForeignKeyConstraint(['rep_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotes')
    op.drop_table('products')
    op.drop_table('audit_logs')
    op.drop_table('user')
    op.drop_table('configurations')
    # ### end Alembic commands ###
